version: 2.1

jobs:
  build_and_push:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
      - checkout
      - run:
          name: Verify .NET SDK
          command: |
            dotnet --info
      - run:
          name: Restore dependencies
          command: dotnet restore
      - run:
          name: Build
          command: dotnet build --configuration Release --no-restore
      - run:
          name: Test
          command: dotnet test --no-restore --verbosity normal
      - run:
          name: Pack
          command: |
            BASE_VERSION=$(grep -oP '(?<=<Version>)\d+\.\d+\.\d+' SolidCqrsFramework.csproj)
            dotnet pack --no-restore --configuration Release --output ./nupkgs /p:Version=${BASE_VERSION}.${CIRCLE_BUILD_NUM}
      - run:
          name: Push
          command: dotnet nuget push ./nupkgs/*.nupkg --api-key ${GITHUB_TOKEN} --source https://nuget.pkg.github.com/${CIRCLE_PROJECT_USERNAME}/index.json --skip-duplicate

workflows:
  version: 2
  build:
    jobs:
      - build_and_push:
          context: ExpertsCircle_Prod
          filters:
            branches:
              only:
                - main
                - master
